language: python
python:
  - "2.7"
install:
    - pip install -r requirements.txt
script:
    - inv test
    - inv coverage
    - python setup.py build
    - python setup.py sdist
after_success:
    - coveralls
notifications:
    email: false
